### PR TITLE
Updated Screenshots #1

### PR DESCRIPTION
**Pull request by gouri-panda**

### CODE REVIEW

**Comment by saumya1singh** [comment]
@gouri-panda  Great Work 🎉

**Comment by saumya1singh** [comment]
@gouri-panda  Just squash these commits into one and you will be ready to go .

**Comment by saumya1singh** [comment]
@gouri-panda  Don't forget to get yourself registerd at KOSS'19  [KOSS-IIT](https://kwoc.kossiitkgp.org/)

And join our slack channel  - https://join.slack.com/t/fitofy-saumyasingh/shared_invite/enQtODU2MDg5MTk5MDcyLTdkNTU5YmNiNmFkOTFkZjY4M2NkNjUzYjY3NzFjNGQyYzQ2M2ZkZDY2OGZlYzE0OWZjNGVmYWNiMzVlNjQ1MGY

**Comment by gouri-panda** [comment]
Squashed these commits

**Pull request closed without merging**
